from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SC = HERE / "schema_coverage" / "results"
RF = HERE / "resample_fidelity" / "results"
AO = HERE / "annotation_overlap" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _table(md: str, startswith: str) -> str:
    lines = md.splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(startswith))
    return "\n".join(lines[start:])


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    sc = _read(SC / "results.json")
    rf = _read(RF / "results.json")
    ao = _read(AO / "results.json")
    sc_md = (SC / "results.md").read_text(encoding="utf-8")
    rf_md = (RF / "results.md").read_text(encoding="utf-8")
    ao_md = (AO / "results.md").read_text(encoding="utf-8")
    cost = (
        f"- Sample rebuild: five 30 s EDFs, committed, no network.\n"
        f"- Resample harness: {rf['duration_sec']} s @ {rf['src_hz']} Hz, "
        f"seed {rf['seed']}.\n"
        f"- Default resampler: {rf['default_method']}.\n"
        "- TUH rsync time/size: unmeasured.\n"
        "- No API calls."
    )
    return (
        template.replace("{{SCHEMA_TABLE}}", _table(sc_md, "| field |"))
        .replace(
            "{{SCHEMA_DECISION}}",
            f"Required core = {', '.join(sc['required_fields'])}. "
            f"Optional = {', '.join(sc['optional_fields'])}.",
        )
        .replace("{{RESAMPLE_TABLE}}", _table(rf_md, "| method |"))
        .replace("{{RESAMPLE_DECISION}}", str(rf["decision"]))
        .replace("{{ANNOT_SUMMARY}}", ao_md.strip())
        .replace("{{ANNOT_DECISION}}", str(ao["decision"]))
        .replace("{{COST_MODEL}}", cost)
    )


def render_eval() -> str:
    p3 = ROOT / "research" / "phase3" / "results" / "results.md"
    extra = p3.read_text(encoding="utf-8") + "\n" if p3.exists() else ""
    return (
        "# Evaluation (Phases 0–3)\n\n"
        "Regenerated by `make eval`. TUH is not downloaded; the transfer matrix "
        "is unmeasured.\n\n"
        + extra
        + (SC / "results.md").read_text(encoding="utf-8")
        + "\n"
        + (RF / "results.md").read_text(encoding="utf-8")
        + "\n"
        + (AO / "results.md").read_text(encoding="utf-8")
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    path = ROOT / "README.md"
    if not path.exists():
        return
    rf = _read(RF / "results.json")
    sc = _read(SC / "results.json")
    ao = _read(AO / "results.json")
    p3_path = ROOT / "research" / "phase3" / "results" / "results.json"
    if p3_path.exists():
        p3 = _read(p3_path)
        transfer = "not run (TUH not downloaded)"
        convert_note = ("ok" if p3.get("clean_convert_ok") else "fail") + (
            "; unit_scale rejects bad-units" if p3.get("bad_units_rejected") else ""
        )
    else:
        transfer = "Phase 3"
        convert_note = "Phase 3"
    body = (
        "| Measurement | Result | Baseline |\n"
        "| --- | --- | --- |\n"
        f"| Default resampler | {rf['default_method']} | naive decimate |\n"
        f"| Required canonical fields | {len(sc['required_fields'])} | all 21 required |\n"
        f"| Unified flat annotation enum | "
        f"{'yes' if ao['unified_flat_enum_achievable'] else 'no'} "
        f"(mean Jaccard {ao['mean_offdiagonal_jaccard']:.3f}) | assume yes |\n"
        f"| Designed-clip convert | {convert_note} | silent unit/channel errors |\n"
        f"| Cross-dataset transfer matrix | {transfer} | unharmonized MNE |\n"
    )
    path.write_text(
        _replace_block(
            path.read_text(encoding="utf-8"),
            "<!-- EVAL_TABLE_BEGIN -->",
            "<!-- EVAL_TABLE_END -->",
            body,
        ),
        encoding="utf-8",
    )


def main() -> None:
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(render_memo(), encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    patch_readme()
    print("wrote memo, EVALUATION.md, README results")


if __name__ == "__main__":
    main()
